In [1]:
# Array Initialization
# numpy.empty(shape, dtype=float, order='C'), shape means dimension
import numpy as np
a = np.empty([2, 2], dtype = int)
print("Matrix a:\n", a)
b = np.empty(2, dtype = int)
print("Matrix b:\n", b)
# The contents of the array will be random, as they depend on the existing memory where the array is allocated.

Matrix a:
 [[            0 2435949951248]
 [2435949951168 2435949953168]]
Matrix b:
 [8367799594051972211 4208162443100185960]


In [2]:
# numpy.zeros(shape, dtype = None, order = 'C)
a = np.zeros([2, 2], dtype = int)
print("Matrix a:\n", a)
b = np.zeros(2, dtype = int)
print("Matrix b:\n", b)
c = np.zeros([3, 3])
print("Matrix c:\n", c)

Matrix a:
 [[0 0]
 [0 0]]
Matrix b:
 [0 0]
Matrix c:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
# Addition
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
add_ans = a+b
print(add_ans)
add_ans = np.add(a, b)
print(add_ans)
c = np.array([1, 2, 3, 4])
add_ans = a+b+c
print(add_ans)
add_ans = np.add(np.add(a, b), c)
print(add_ans)

[  7  77  23 130]
[  7  77  23 130]
[  8  79  26 134]
[  8  79  26 134]


In [4]:
# Subtraction
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
add_ans = a-b
print(add_ans)
add_ans = np.subtract(a, b)
print(add_ans)
c = np.array([1, 2, 3, 4])
add_ans = a-b-c
print(add_ans)
add_ans = np.subtract(np.subtract(a, b), c)
print(add_ans)

[ 3 67  3 70]
[ 3 67  3 70]
[ 2 65  0 66]
[ 2 65  0 66]


In [5]:
# Multiplication
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
div_ans = a*b
print(div_ans)
div_ans = np.multiply(a, b)
print(div_ans)

[  10  360  130 3000]
[  10  360  130 3000]


In [6]:
# Division
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
div_ans = a/b
print(div_ans)
div_ans = np.divide(a, b)
print(div_ans)

[ 2.5        14.4         1.3         3.33333333]
[ 2.5        14.4         1.3         3.33333333]


In [7]:
# Array Indexing
a = np.arange(10, 1, -2)
print("A sequential array with a negative step:\n", a)
newarr = a[np.array([3, 1, 2])]
# np.array([3, 1, 2]): Creates a 1D NumPy array containing the indices [3, 1, 2]
print("Elements at these indices are:\n", newarr)

A sequential array with a negative step:
 [10  8  6  4  2]
Elements at these indices are:
 [4 8 6]


In [8]:
# Array Slicing
a = np.arange(20)
print("Array is:")
print("a[-8:17:1] = ", a[-8:17:1])
# -8: Start index, 17: End index, 1: Step size.
print("a[10:] = ", a[10:])

Array is:
a[-8:17:1] =  [12 13 14 15 16]
a[10:] =  [10 11 12 13 14 15 16 17 18 19]


In [9]:
# Ellipsis Method
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
new_array = b[..., 1]
print(new_array)

[[ 2  5]
 [ 8 11]]


In [10]:
# Array Broadcasting
# Example 1:
a = np.array([1, 2, 3]) # shape(3,)
b = 2 # scalar, shape()
result = a*b
print(result)
# The scalar b is broadcasted to match the shape a, so it operates like: [2, 2, 2]

[2 4 6]


In [11]:
# Example 2: Arrays of different shapes
a = np.array([[1, 2, 3], [4, 5, 6]]) # shape(2, 3)
b = np.array([10, 20, 30]) # shape(3,)
result = a+b
print(result)
# The shape(3,) of b is broadcasted to (2, 3) to match a, so b is treated like: [[10, 20, 30], [10, 20, 30]]

[[11 22 33]
 [14 25 36]]


In [12]:
# Example 3: Higher Dimensions
a = np.array([1, 2, 3])  # Shape (3,)
b = np.array([[10], [20]])  # Shape (2, 1)
result = a + b
print(result)
# The shapes (3,) and (2, 1) are broadcasted to (2, 3).

[[11 12 13]
 [21 22 23]]


In [13]:
# With this transformation, we can now compute all kinds of useful information. 
# For example, what is the total number of calories present in some food or, 
# given a breakdown of my dinner know how many calories did I get from protein and so on.
macros = np.array([[0.8, 2.9, 3.9], [52.4, 23.6, 36.5], [55.2, 31.7, 23.9], [14.4, 11, 4.9]])
cal_per_macro = np.array([3, 3, 8])
result = macros * cal_per_macro
print(result)

[[  2.4   8.7  31.2]
 [157.2  70.8 292. ]
 [165.6  95.1 191.2]
 [ 43.2  33.   39.2]]


In [14]:
v = np.array([12, 24, 36])
w = np.array([45, 55])
print(np.reshape(v, (3, 1))*w)
X = np.array([[12, 22, 33], [45, 55, 66]])
print(X+v)
print((X.T+w).T)
print(X*2)

[[ 540  660]
 [1080 1320]
 [1620 1980]]
[[ 24  46  69]
 [ 57  79 102]]
[[ 57  67  78]
 [100 110 121]]
[[ 24  44  66]
 [ 90 110 132]]
